name = 'FoxTech'
license = 'MIT'
licenselink = 'https://github.com/FoxTechWorld/FoxTech/LICENSE'
description = 'A minimalist dark theme being used in blog'

tags = ['blog', 'dark', 'minimalist']
features = ['SEO Optimized', 'dark', 'bootstrap']

[author]
  name = 'KitsuneSemCalda <arthuramagalhaes1312@gmail.com>'
  homepage = 'FoxTechWorld.github.io'